# Generated by Django 4.2 on 2023-04-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_author_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
